### ISSUE TITLE
pretrained backbone

### ISSUE THREAD

**Issue by Nocoffeeanymore** [D3lt4lph4/jpeg_deep#6]
Hello~
Thanks for sharing your work. You mentioned that "a better pretrained backbone" to improve the mAP from 0.48 to 0.60 in your paper.  May you give me some more details about this?

**Comment by D3lt4lph4** [comment]
Hi,

Sure, in the [previous article](https://arxiv.org/abs/1904.08408) we ended up training (for various reasons) detection networks that were initialized with backbones not fully converged (and hence not having the best accuracy).

After some testing it seems that the mAP is highly dependent on the accuracy of the backbone with which it is initialized. Because in this article we used a backbone that we had time to fully train, the accuracy of the detection network went up.

Hope this answer your question !

**Comment by Nocoffeeanymore** [comment]
Thank you, dear author~
